/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        role: ['ADMIN', 'INTERNAL_USER'],
        link: '/dashboard',
    },
    {
        id: 'user',
        title: 'Users',
        type: 'basic',
        icon: 'heroicons_outline:user',
        role: ['ADMIN'],
        link: '/user',
    },
    {
        id: 'invoices',
        title: 'Invoices',
        type: 'group',
        icon: 'heroicons_outline:rectangle-stack',
        role: ['INTERNAL_USER'],
        children: [
            {
                id: 'invoices.all',
                title: 'All Invoices',
                type: 'basic',
            },
            {
                id: 'invoices.outstanding',
                title: 'Invoices Outstanding',
                type: 'basic',
            },
            {
                id: 'invoices.paid',
                title: 'Invoices Paid',
                type: 'basic',
            },
            {
                id: 'invoices.queried',
                title: 'Invoices Queried',
                type: 'basic',
            },
        ],
    },
    {
        id: 'customer',
        title: 'Customers',
        type: 'basic',
        icon: 'heroicons_outline:user',
        role: ['ADMIN', 'INTERNAL_USER'],
        link: '/customer',
    },
    {
        id: 'branch',
        title: 'Branches',
        type: 'basic',
        icon: 'heroicons_outline:home',
        role: ['ADMIN'],
        link: '/branch',
    },
    {
        id: 'messages',
        title: 'Messages',
        type: 'group',
        icon: 'heroicons_outline:envelope',
        role: ['INTERNAL_USER'],
        children: [
            {
                id: 'messages.received',
                title: 'Messages Received',
                type: 'basic',
            },
            {
                id: 'messages.sent',
                title: 'Messsages Sent',
                type: 'basic',
            },
        ],
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        tooltip: 'Dashboard',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'user',
        title: 'Users',
        tooltip: 'Users',
        type: 'basic',
        role: ['ADMIN'],
        icon: 'heroicons_outline:user',
        link: '/user',
    },
    {
        id: 'invoices',
        title: 'Invoices',
        tooltip: 'Invoices',
        type: 'group',
        icon: 'heroicons_outline:rectangle-stack',
        role: ['INTERNAL_USER'],
        children: [],
    },
    {
        id: 'customer',
        title: 'Customers',
        tooltip: 'Customers',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        icon: 'heroicons_outline:user',
        link: '/customer',
    },
    {
        id: 'branch',
        title: 'Branches',
        tooltip: 'Branches',
        type: 'basic',
        role: ['ADMIN'],
        icon: 'heroicons_outline:home',
        link: '/branch',
    },
    {
        id: 'messages',
        title: 'Messages',
        tooltip: 'Messages',
        type: 'group',
        icon: 'heroicons_outline:envelope',
        role: ['INTERNAL_USER'],
        children: [],
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        tooltip: 'Dashboard',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        link: '/dashboard',
    },
    {
        id: 'user',
        title: 'Users',
        tooltip: 'Users',
        type: 'basic',
        role: ['ADMIN'],
        link: '/user',
    },
    {
        id: 'invoices',
        title: 'Invoices',
        type: 'group',
        role: ['INTERNAL_USER'],
        children: [],
    },
    {
        id: 'customer',
        title: 'Customers',
        tooltip: 'Customers',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        link: '/customer',
    },
    {
        id: 'branch',
        title: 'Branches',
        tooltip: 'Branches',
        type: 'basic',
        role: ['ADMIN'],
        link: '/branch',
    },
    {
        id: 'messages',
        title: 'Messages',
        type: 'group',
        role: ['INTERNAL_USER'],
        children: [],
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        tooltip: 'Dashboard',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'user',
        title: 'Users',
        tooltip: 'Users',
        type: 'basic',
        role: ['ADMIN'],
        icon: 'heroicons_outline:home',
        link: '/user',
    },
    {
        id: 'invoices',
        title: 'Invoices',
        tooltip: 'Invoices',
        type: 'group',
        icon: 'heroicons_outline:rectangle-stack',
        role: ['INTERNAL_USER'],
        children: [],
    },
    {
        id: 'customer',
        title: 'Customers',
        tooltip: 'Customers',
        type: 'basic',
        role: ['ADMIN', 'INTERNAL_USER'],
        icon: 'heroicons_outline:user',
        link: '/customer',
    },
    {
        id: 'branch',
        title: 'Branches',
        tooltip: 'Branches',
        type: 'basic',
        role: ['ADMIN'],
        icon: 'heroicons_outline:home',
        link: '/branch',
    },
    {
        id: 'messages',
        title: 'Messages',
        tooltip: 'Messages',
        type: 'group',
        icon: 'heroicons_outline:envelope',
        role: ['INTERNAL_USER'],
        children: [],
    },
];
